#sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
#  - sudo apt upgrade docker-ce
#  - wget https://raw.githubusercontent.com/bestlibre/hassio-addons/master/build.sh -O build.sh
  - chmod u+x build.sh
#  - wget https://raw.githubusercontent.com/home-assistant/hassio-build/master/build-scripts/addons/create_hassio_addon.sh -O create_hassio_addon.sh
#  - chmod u+x create_hassio_addon.sh
#  - docker pull multiarch/qemu-user-static
# for docker to work with the alpine arm images, we need a newer libseccomp on host (at least 2.4.2)
  - wget http://ftp.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_amd64.deb
  - dpkg -i libseccomp2_2.5.1–1_amd64.deb
env:
  - ADDON="pyhpsu2mqtt"
#  - ADDON="vzlogger"
script:
#  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./build.sh $ADDON 
